import type { ChannelOp, PaletteEntry, SlotMap, ThemeDef } from "../dsl/types.js";
import type { DerivedPair } from "./derive.js";

/** kebab-slug → camelCase identifier stem. */
function ident(name: string): string {
  return name.replace(/-([a-z0-9])/g, (_, ch: string) => ch.toUpperCase());
}

function entryLine(name: string, e: PaletteEntry): string {
  return `  ${name}: { l: ${e.l}, c: ${e.c}, h: ${e.h} },`;
}

function slotsLiteral(slots: SlotMap): string {
  return (Object.entries(slots) as [string, string][])
    .map(([k, v]) => `  ${k}: "${v}",`)
    .join("\n");
}

function opLiteral(op: ChannelOp): string {
  return `${op.op}(${op.value})`;
}

/**
 * Serialize the solved AA overrides.
 *
 * These are NOT optional decoration. The default theme formulas fail the
 * contrast matrix on most generated palettes — that is the entire reason
 * `solveOverrides` exists — so a `customers/<name>.ts` emitted without them
 * would not merely render differently from the console preview: it would
 * throw in the token build, whose WCAG gate runs over every committed theme.
 * An unbuildable file is not "a real customer theme out".
 *
 * The emitted shape matches `acmeOverrides` in `customers/acme.ts`, which
 * carries exactly this kind of per-hue correction by hand.
 */
function overridesLiteral(overrides: ThemeDef): string {
  return Object.entries(overrides)
    .map(([name, def]) => {
      const parts: string[] = [];
      if (def.from.type === "slot") parts.push(`from: slot.${def.from.name}`);
      else parts.push(`from: ref.${def.from.name}`);
      if (def.l) parts.push(`l: ${opLiteral(def.l)}`);
      if (def.c) parts.push(`c: ${opLiteral(def.c)}`);
      if (def.h) parts.push(`h: ${opLiteral(def.h)}`);
      if (def.alpha !== undefined) parts.push(`alpha: ${def.alpha}`);
      if (def.scopes) parts.push(`scopes: ${JSON.stringify(def.scopes)}`);
      return `  ${name}: token({ ${parts.join(", ")} }),`;
    })
    .join("\n");
}

/**
 * Emit the `customers/<name>.ts` source for a derived pair, plus the two lines
 * that register it. Shape matches `scripts/new-theme.ts`, extended to a pair.
 */
export function serializeCustomerTheme(pair: DerivedPair): {
  filename: string;
  source: string;
  registration: string;
} {
  const { vector, light, dark } = pair;
  const id = ident(vector.name);
  const palette = light.customerTheme.palette;
  const radius = `var(--psi-radius-${vector.radius})`;

  const source = `import { cap, delta, ref, set, slot, token } from "../../dsl/builders.js";
import type { Palette, SlotMap, ThemeDef } from "../../dsl/types.js";

// Generated by the Psi theme console from the prompt:
//   "${vector.name.replace(/-/g, " ")}"
// Every pair in the WCAG AA matrix is solved, in both modes, by construction.

export const ${id}Palette: Palette = {
${Object.entries(palette).map(([n, e]) => entryLine(n, e)).join("\n")}
};

/** Light member — ink is dark, canvas is light. */
export const ${id}Slots: SlotMap = {
${slotsLiteral(light.customerTheme.slots)}
};

/** Dark member — the same brand hue, lightness anchors inverted. */
export const ${id}DarkSlots: SlotMap = {
${slotsLiteral(dark.customerTheme.slots)}
};

/** Solved AA corrections for the light member. Without these the default
 * formulas miss the contrast matrix on this palette and the build throws. */
export const ${id}Overrides: ThemeDef = {
${overridesLiteral(light.customerTheme.overrides ?? {})}
};

/** Solved AA corrections for the dark member. */
export const ${id}DarkOverrides: ThemeDef = {
${overridesLiteral(dark.customerTheme.overrides ?? {})}
};

/** One dial for control shape (D56). */
export const ${id}ComponentOverrides: Record<string, string> = {
  "control-radius": "${radius}",
};
`;

  const registration = `  ${vector.name}: { palette: ${id}Palette, slots: ${id}Slots, overrides: ${id}Overrides, componentOverrides: ${id}ComponentOverrides },
  "${vector.name}-dark": { palette: ${id}Palette, slots: ${id}DarkSlots, base: "dark", overrides: ${id}DarkOverrides, componentOverrides: ${id}ComponentOverrides },`;

  return { filename: `${vector.name}.ts`, source, registration };
}
